### PR TITLE
Fixes for MSW cross-compilation

### PR DESCRIPTION
**Pull request by vadz**
With these changes, running

    ~/src/wxpdfdoc/configure --host=i686-w64-mingw32 --with-wx-confi=~/build/wx/msw/wx-config

and then `make` works and produces apparently working MSW executables for the samples.

### CODE REVIEW

**Comment by utelle** [comment]
In general, I'm fine with your proposed changes.

However, one possible issue comes to my mind. For the Windows build system (Visual C++, MinGW) I defined 3 configurations:

- wxPdfDocument as static library, wxWidgets as static library
- wxPdfDocument as static library, wxWidgets as DLL
- wxPdfDocument as DLL, wxWidgets as DLL

In the second case one has to define the preprocessor symbol `WXUSINGLIB_PDFDOC`. Depending on which configurations will be supported for cross-compilation, it might be necessary to add this symbol definition.

**Comment by vadz** [comment]
I'm looking at the current block of code in `pdfdocdef.h` and I just don't understand its logic. Why should we define `WXDLLIMPEXP_PDFDOC` as "import" when using wx as DLL? IMO it should be just
```
#if defined(WXMAKINGDLL_PDFDOC)
  #define WXDLLIMPEXP_PDFDOC WXEXPORT
  #define WXDLLIMPEXP_DATA_PDFDOC(type) WXEXPORT type
#elif defined(WXUSINGDLL_PDFDOC)
  #define WXDLLIMPEXP_PDFDOC WXIMPORT
  #define WXDLLIMPEXP_DATA_PDFDOC(type) WXIMPORT type
#else // not making nor using DLL
  #define WXDLLIMPEXP_PDFDOC
  #define WXDLLIMPEXP_DATA_PDFDOC(type) type
#endif
```

Am I missing something here?

**Comment by utelle** [comment]
The "logic" was invented maybe 10 years ago and - AFAICR - was influenced by some weird wxCode ideas about supporting all possible combinations of static and DLL builds for the component and wxWidgets.

Probably it should be changed as you proposed.

Nevertheless, for wxPdfDocument DLL builds for the samples it will be necessary to define the symbol `WXUSINGDLL_PDFDOC`.

**Comment by vadz** [comment]
1. I think this logic was wrong even 10 years ago because `WXUSINGDLL` is just irrelevant here: what counts for defining `WXDLLIMPEXP_PDFDOC` is whether `WXUSINGDLL_PDFDOC` is defined or not (or, if you prefer to assume DLL use by default, if none of `WXMAKINGLIB_PDFDOC`, `WXMAKINGDLL_PDFDOC` and `WXUSINGLIB_PDFDOC` is defined).
1. Defining `WXUSINGDLL_PDFDOC` seems tricky, unfortunately, as it must only be specified if the shared library is being built and libtool doesn't provide any simple way to do this. I'll check if I can find a not simple one, but right now things link even without it (and with wrong definitions in `wx/pdfdocdef.h`) because all recent binutils versions support auto-linking, i.e. they don't really need DLL import declarations at all.

**Comment by utelle** [comment]
1. I already changed my local version of `pdfdocdef.h` to use only `WXMAKINGDLL_PDFDOC` and `WXUSINGDLL_PDFDOC`. I can't recall what exactly my reasoning was over 10 years ago. Probably it was some misconception due to being new to wxWidgets back then. Be that as it may ... I will commit the change soon.

2. The symbol `WXMAKINGDLL_PDFDOC` is required when building the shared library. The symbol `WXUSINGDLL_PDFDOC` is required when building the executables like the minimal sample. Not sure, whether they are required when cross-compiling.

**Comment by vadz** [comment]
`WXMAKINGDLL_PDFDOC` is always required under MSW, because the symbols exported from the DLL must use `WXEXPORT` in their declaration. But `WXUSINGDLL_PDFDOC` is not actually required because binutils linker is smart enough now to look for the imported version of the symbol if it doesn't find the normal one (this is called auto-linking).

But, anyhow, I think I could make it work in a rather straightforward way, finally. I'll finish testing it and update this PR soon.

**Comment by vadz** [comment]
FYI: I tested cross-building only static, only shared and both static and shared versions of the library and they all built fine (and the resulting samples could be run).

**Comment by utelle** [comment]
Great news. Thanks.

I will merge the PR.

P.S.: Changes to the Windows specific build files for Visual C++ will follow as mentioned in PM.

**Pull request merged**
