### PR TITLE
Whitespace fixes

### PR DESCRIPTION
**Pull request by vadz**
These changes are purely cosmetic, but I think it's still worth doing them in order to get all (source) files into their "canonical" form, i.e. Unix EOLs and no trailing whitespace.

There are no non-whitespace changes here as can be checked using `git diff -w` or appending `w=1` to the URL when examining the diff on GitHub, i.e. like this: https://github.com/utelle/wxpdfdoc/pull/28/files?w=1

### CODE REVIEW

**Comment by utelle** [comment]
I have to admit that I had - obviously erroneously - assumed that git / github takes care automatically of the line endings and that source release downloads in ZIP format have Windows line endings and those in tarball format have Linux line endings.

I agree that the line ending settings in github should be such that all users are happy with them. OTOH I prefer to have Windows line endings under Windows, since I experienced obscure problems in the past if that was not the case. I'm using TortoiseGit for git integration, but I'm not sure which option(s) to set to get the result I want.

Would it be an option to introduce a .gitattributes file to define the line endings behaviour?

Of course, I'm fine with removing trailing whitespace. Most probably it was introduced by older versions of MSVC, for which I had not adjusted the editor settings.

**Comment by vadz** [comment]
I think it would be better to have a local `.git/info/attributes` instead as some people (e.g. me) would really prefer to use Unix EOLs even under MSW, e.g. because I use Cygwin which really prefers them.

Honestly, I don't think there are any Windows tools not dealing with the Unix EOLs left, except for notepad but, well, hopefully nobody edits sources in it.

Maybe you could try working with this branch and see if you encounter any problems? The only one I see now is with the ZIP files, but I think the best way to fix this would be to just call `unix2dos` on them when preparing it. I'm not sure how do you do it though, so I don't know how to do it exactly. Of course, if you have a local `.git/info/attributes` with `*.cpp eol=crlf` (and the same thing for `.h` and `.inc` files), then it should work without any further changes.

**Comment by utelle** [comment]
I tested to check out your branch using various git settings (`autocrlf=true` vs `autocrlf=false`). This works mostly as expected.

However, IMHO a `.gitattributes` file would make sense, since we have several files for which we definitely want a specific line ending, namely the MSVC project files should definitely have CRLF line endings.

Maybe you could add the following `.gitattributes` file to your branch `whitespace-fixes` so that I could test whether this has the intended effect:
```
# Set default behaviour to automatically normalize line endings.
* text=auto

# Source files
*.cpp text
*.h text
*.inc text
*.rc text
*.lua text

# Font files
*.afm text
*.map text
*.otf binary
*.pfb binary
*.ttf binary
*.ufm text
*.xml text
*.z binary

# Resource files
*.gif binary
*.html text
*.ico binary
*.jpg binary
*.pdf binary
*.png binary
*.txt text
*.wmf binary
*.xpm text

# MSVC project files
*.sln text eol=crlf
*.vcxproj text eol=crlf
*.props text eol=crlf
*.filters text eol=crlf
```

Regarding the ZIP and tarball files in releases these are automatically generated by github. And it seems that github always uses the line endings as they are in the repository. That is, except for the archive format the content of the archives is exactly identical.

**Comment by vadz** [comment]
These commits don't touch the project/solution files, so they keep their CR LFs and there is no need to do anything for them, why should we bother converting them?

We could have such an attributes file and you can just put it in your local `.git/info` for testing, but I really don't see what do we gain from it.

As for ZIP archives, they would indeed contain files with Unix EOLs if you just use GitHub built-in functionality. But this IMO still preferable to having DOS EOLs in the tarballs: while all Windows tools I know handle Unix EOLs fine, many Unix tools do not handle DOS EOLs correctly, i.e. for them `CR` is just another character and nothing special, which can be really confusing (e.g. because `\` at the end of line might not be seen as a line continuation etc).

**Comment by utelle** [comment]
Of course I see that your commits don't touch the project files. Nevertheless, I think the gain from an `.gitattributes` file would be that adding accidentally a new source file with _wrong_ line endings will be prevented. As you know I work mostly under Windows, and the default line ending under Windows is CRLF. That is, it could easily happen that a newly created source file is committed with CRLF line endings. 

To prevent the latter I could set `autocrlf=true` for my local repository. However, that would affect also newly added project files (which would then be normalized to LF line endings, too). I don't see how this could be solved without using a `.gitattributes` file.

Regarding the ZIP and tarball archives I fully agree. I was not aware of the fact that the tarballs generated by GitHub automatically use CRLF as line endings, if the repository is not normalized to LF.

**Comment by vadz** [comment]
> That is, it could easily happen that a newly created source file is committed with CRLF line endings.

Ah, I see. Unfortunately (although understandably) GitHub doesn't support custom hooks, but this could still be addressed by just having a `pre-commit` hook checking for CRs in any source files staged for commit and refusing to proceed. IMO this would be better than using files with CRLF in the working copy and converting them to/from LF on check in/out.

**Comment by utelle** [comment]
Your approach requires that all contributors are behaving well, add such an `pre-commit` hook or take other measures to force LFs as line endings in new source files.

Although Visual Studio can handle source files with Unix line endings, you can't enforce that newly created source files use Unix line endings. In contrary, Windows line endings will be used for new files, unless you install one of the available Visual Studio extension that allow you to address this problem.

For myself, I can install such an extension, and I probably will. However, as I see it, the only way to enforce proper line endings is to use a `.gitattributes` file. This still allows to enable or disable line ending conversion for your local repository using local git options (namely `autocrlf`).

**Comment by vadz** [comment]
I guess I can live with this `.gitattributes` in the repo, although I'd have to override it with my own one in `.git/info` to avoid CRLFs locally. But in any case this PR should still be applied IMHO, as it's better to start with all files in the repo normalized to LF.

Also, I think worries about multitudes of badly behaving contributors are a bit exaggerated, we could deal with this problem once it really happens...

**Comment by utelle** [comment]
I merged your PR. However, I will add a `.gitattributes` file to reduce the chance to accidentally commit files with conflicting line endings.

**Pull request merged**
