### PR TITLE
Regenerate all configure scripts and update the dependent files

### PR DESCRIPTION
**Pull request by vadz**
Add bakefile and wxCode files needed for updating the build system: copy *.m4
files from Bakefile 0.2.9 (the latest and last 0.x release) and the relevant
contents of wxCode/build into this repository.

Update the paths in build*/configure.ac and Bakefiles.bkgen to refer to the
files in this repository.

Regenerated build*/aclocal.m4 files using the latest aclocal (this, in
particular, means that they just include the files they use instead of
incorporating them) and wxwin.m4.

The latter is especially important as it ensures that wxPdfDocument can be
used with wxGTK3 which wasn't recognized by the macros in the old version of
this file.

### CODE REVIEW

**Comment by utelle** [comment]
Vadim, thanks for the big effort you did to bring the bakefile based build system up-to-date and make it independent of the wxCode files.

I mostly agree with all changes. However, before merging the pull request I'd like to understand resp. clarify a few points.

1) While I fully understand why you pull in the wxCode build files, I'd like to understand how and when the files in the admin folder are needed.

2) Now, that wxWidgets 3.0.x is the current wxWidgets version, it probably would make sense to rename the folder "build" to "build28" as it is meant to build the library for wxWidgets 2.8.x.

3) Maybe we could drop folder "build29" completely. I added it when wxWidgets 3.x did not yet exist. I never used 2.9 for any productive use. So, how important is it to keep this folder?

4) Now, that wxPdfDocument in fact moved away from wxCode, would it make sense to drop the "wxcode" part from the name of the generated libraries? Currently we have names like "wxcode_msw30ud_pdfdoc.lib". I.e. that could be changed to "wxpdfdoc_msw30ud.lib". What do you think?

**Comment by vadz** [comment]
I basically just tried to make the smallest possible amount of changes allowing me to use the library with wxGTK3. Further changes/improvements are definitely possible and maybe even needed.

1. The files in `admin/aclocal` are needed if you need to rerun `aclocal` to update `build*/aclocal.m4` files. E.g. in `build30` you should run it as `aclocal -I ../admin/aclocal`.
1. Yes, at the very least I'd rename `build` to `build28` as it's inconsistent with the name of `configure` and `Makefile.in` where the version-less variants correspond to 3.0.
1. Perfectly fine with dropping it.
1. This would be more logical but would also break compatibility with the existing make/project files using the library. I don't know how important is this consideration for you...

**Comment by utelle** [comment]
Thanks for clarification.

I merged your pull request. Then I renamed build to build28 and removed build29.

Regarding the name of the library I think I would prefer to rename it. However, this would probably require to adjust the wxCode presets somehow as I think the full library name is constructed somewhere in those presets.

**Comment by vadz** [comment]
Yes, sorry, changing the name won't be so simple as it's constructed [deep inside](https://github.com/utelle/wxpdfdoc/blob/master/wxcode/bakefiles/presets/templates.bkl#L60) wxCode bakefiles. I don't know how to change this, in fact this doesn't seem to be possible. Of course, you could just hack the presets themselves...

**Comment by utelle** [comment]
The creation of wx-like library names seems to be a feature of bakefile. And it doesn't seem to be easy to change, I agree. Well, for the time being I will therefore not change the name.

**Pull request merged**
