### PR TITLE
pdfxml: Check if image fits on page

### PR DESCRIPTION
**Pull request by stkruse**
When creating a pdf from a xml string no decision is made if the image fits on the page. I added some lines for checking if the image fits on the page and adding a new page  containing the image if not.

### CODE REVIEW

**Comment by utelle** [comment]
In principle, I agree that checking whether the image fits into the remaining space on the current page, makes sense. 

On the other hand, I'm not so sure whether always forcing a page break if the image doesn't fit, is the right solution. That might not be the intended behaviour - for example, if auto page break was turned off.

So probably it should be also checked whether auto page break mode is on or off.

And then there is another special case, namely if the image size is so big that it doesn't fit on the page even after a page break. Again, it's not clear what the best approach would be. Even if the image is the first item on a page, your patch would add an empty page in such a case. Certainly not a common case, but it should be taken into account as well.

If we start checking then it should probably also be checked whether the image is wider than the page width.

Another option would be to rescale the image, so that it fits on the page.

Maybe adding option attributes to the image tag would be the most flexible approach allowing the user to decide what should happen in case the image doesn't fit.

**Comment by stkruse** [comment]
I wasn't aware of the auto page break mode. If there is a special mode which forbids a page break, it should be tested for sure.
If the image doesn't fit on one page there is no "natural" way to display it, so in my opinion adding a page would be okay in this case.

I think rescaling is only a possible solution if no specific image size is given by option attributes. And this case is broken anyway, because following content overlays the included image. 

Adding option attributes for this case is probably the best solution but would make your markup language less similar to HTML.

**Comment by utelle** [comment]
The `AutoPageBreak` mode definitely would have to be taken into account. Whether it is enabled or not, can be checked with method `AcceptPageBreak`. 

Additionally, it has to be checked whether the page footer is currently processed. Adding a page while processing the page footer would result in a recursive invocation, and finally to a crash of the application. Method `IsInFooter` can be used to check the state.

However, the main problem is that neither width nor height need to be specified in the image tag. The values will be set implicitly to zero, and the image will be scaled according to its real size. Quite often only width is specified to force a certain width independently of the real image width, but to keep the aspect ratio. That is, in such a case checking the height value would not trigger a page break, even if it should. Unfortunately the real image size is not known in advance - at least at the moment.

The markup language supported by wxPdfDocument is not meant to support rendering of arbitrary HTML pages. That is, adding specific attributes could be justifiable.

The critical deficiency of the image tag is probably that the coordinates of the output position is currently not updated appropriately after outputting the image. This could - and probably should - be corrected.

In fact, handling the image tag in a reasonable and reliable way involves far more than just checking the width and height attributes of the tag.

**Comment by utelle** [comment]
In its current form I will not apply this pull request. Please reopen the issue, if you intend to provide an adjusted pull request.

**Pull request closed without merging**
